apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: TimescaleDB
    type: postgres
    url: timescaledb:5432
    database: pulsesense
    user: admin
    secureJsonData:
      password: pulsesense_secure_pass
    isDefault: true
    jsonData:
      database: pulsesense
      sslmode: disable
      timescaledb: true
